spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  database:
    driverClassName: "com.mysql.jdbc.Driver"
  datasource:
    url: "jdbc:mysql://localhost:3306/emdb?createDatabaseIfNotExist=true"
    username: "root"
    password: "root"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"

server:
  port: 8082
  
eureka:
  instance:
    perferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.manojbehera: DEBUG

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/user